version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_ENV=development
    command: >
      sh -c "
      [ ! -d 'migrations' ] && flask db init || echo 'Migrations directory already exists' &&
      flask db migrate -m 'Initial migration.' &&
      flask db upgrade  &&
      flask run --host=0.0.0.0
      "

    